const $=s=>document.querySelector(s), money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let expr='',history=JSON.parse(localStorage.getItem('wosvipHistory')||'[]');
const addHistory=(type,detail,result)=>{history.unshift({type,detail,result,date:new Date().toLocaleString('pt-BR')});history=history.slice(0,100);localStorage.setItem('wosvipHistory',JSON.stringify(history));renderHistory()};
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='history')renderHistory()});
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('wosvipTheme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('wosvipTheme')==='light')document.body.classList.add('light');
const buttons=['sin','cos','tan','√','π','7','8','9','÷','⌫','4','5','6','×','^','1','2','3','−','(','0','.','%','+',')','C','ln','log','±','='];
const keys=$('#keys');buttons.forEach(k=>{const b=document.createElement('button');b.textContent=k;b.className=k==='='?'equal':k==='C'||k==='⌫'?'clear':isNaN(k)&&k!=='.'&&k!=='('?'op':'';b.onclick=()=>press(k);keys.appendChild(b)});
function press(k){if(k==='C')expr='';else if(k==='⌫')expr=expr.slice(0,-1);else if(k==='=')calculate();else if(k==='±')expr=expr?`-(${expr})`:'-';else{const map={sin:'sin(',cos:'cos(',tan:'tan(','√':'sqrt(','π':'pi','÷':'/','×':'*','−':'-','^':'**',ln:'ln(',log:'log('};expr+=map[k]??k}updateDisplay()}
function safeEval(source,x){if(!/^[0-9x+\-*/().,%\s_a-z*]+$/i.test(source))throw Error('Caracteres inválidos');let s=source.replace(/\^/g,'**').replace(/\bpi\b/gi,'Math.PI').replace(/\be\b/g,'Math.E').replace(/\bsin\b/g,'Math.sin').replace(/\bcos\b/g,'Math.cos').replace(/\btan\b/g,'Math.tan').replace(/\bsqrt\b/g,'Math.sqrt').replace(/\bln\b/g,'Math.log').replace(/\blog\b/g,'Math.log10').replace(/\babs\b/g,'Math.abs').replace(/\bexp\b/g,'Math.exp');return Function('x',`"use strict";return (${s})`)(x)}
function calculate(){try{const r=safeEval(expr.replace(/(\d+(?:\.\d+)?)%/g,'($1/100)'));if(!Number.isFinite(r))throw Error();addHistory('Científica',expr,String(+r.toPrecision(12)));expr=String(+r.toPrecision(12));$('#expression').textContent='Resultado'}catch{$('#expression').textContent='Expressão inválida'}updateDisplay()}
function updateDisplay(){$('#screen').value=expr||'0';if(expr)$('#expression').textContent=expr}updateDisplay();
$('#financeCalc').onclick=()=>{const c=+$('#capital').value,r=+$('#rate').value/100,n=+$('#periods').value,t=$('#finType').value;if(c<0||n<=0||!Number.isFinite(r))return;let value,label;if(t==='compound'){value=c*(1+r)**n;label='Montante'}else if(t==='simple'){value=c*(1+r*n);label='Montante'}else{value=r===0?c/n:c*r*(1+r)**n/((1+r)**n-1);label='Parcela'}const interest=t==='payment'?null:value-c;const out=`<strong>${label}: ${money(value)}</strong>${interest!==null?`<br>Juros acumulados: ${money(interest)}`:`<br>Total pago: ${money(value*n)}`}`;$('#financeResult').innerHTML=out;addHistory('Financeira',`${t}: ${money(c)}, ${r*100}% × ${n}`,`${label}: ${money(value)}`)};
const units={Comprimento:{metro:1,quilômetro:1000,centímetro:.01,milímetro:.001,polegada:.0254,pé:.3048,milha:1609.344},Massa:{quilograma:1,grama:.001,miligrama:.000001,tonelada:1000,libra:.45359237,onça:.0283495},Área:{'m²':1,'km²':1e6,'cm²':1e-4,hectare:1e4,'pé²':.092903},Volume:{litro:1,mililitro:.001,'m³':1000,galão:3.785411784},Velocidade:{'m/s':1,'km/h':1/3.6,'mph':.44704},Temperatura:{C:'C',F:'F',K:'K'}};
Object.keys(units).forEach(x=>$('#category').add(new Option(x,x)));function fillUnits(){const u=Object.keys(units[$('#category').value]);['#fromUnit','#toUnit'].forEach((s,i)=>{$(s).innerHTML='';u.forEach(x=>$(s).add(new Option(x,x)));if(i&&u[1])$(s).selectedIndex=1})}$('#category').onchange=fillUnits;fillUnits();
$('#convertCalc').onclick=()=>{const cat=$('#category').value,a=$('#fromUnit').value,b=$('#toUnit').value,v=+$('#convValue').value;let r;if(cat==='Temperatura'){let c=a==='C'?v:a==='F'?(v-32)*5/9:v-273.15;r=b==='C'?c:b==='F'?c*9/5+32:c+273.15}else r=v*units[cat][a]/units[cat][b];const text=`${v.toLocaleString('pt-BR')} ${a} = ${(+r.toPrecision(12)).toLocaleString('pt-BR')} ${b}`;$('#convertResult').textContent=text;addHistory('Conversão',cat,text)};
function plot(){const canvas=$('#graphCanvas'),ctx=canvas.getContext('2d'),fn=$('#functionInput').value,x0=+$('#xMin').value,x1=+$('#xMax').value;$('#graphError').textContent='';if(!(x1>x0))return $('#graphError').textContent='O valor máximo deve ser maior.';let pts=[],ys=[];try{for(let i=0;i<canvas.width;i++){let x=x0+(x1-x0)*i/(canvas.width-1),y=safeEval(fn,x);pts.push([i,y]);if(Number.isFinite(y))ys.push(y)}}catch(e){return $('#graphError').textContent='Função inválida.'}if(!ys.length)return $('#graphError').textContent='Sem valores válidos.';ys.sort((a,b)=>a-b);let y0=ys[Math.floor(ys.length*.02)],y1=ys[Math.floor(ys.length*.98)];if(y0===y1){y0--;y1++}ctx.clearRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#29425b';ctx.lineWidth=1;const py=y=>canvas.height-(y-y0)/(y1-y0)*canvas.height;ctx.beginPath();let zeroY=py(0);ctx.moveTo(0,zeroY);ctx.lineTo(canvas.width,zeroY);let zeroX=(0-x0)/(x1-x0)*canvas.width;ctx.moveTo(zeroX,0);ctx.lineTo(zeroX,canvas.height);ctx.stroke();ctx.strokeStyle='#20d8b4';ctx.lineWidth=3;ctx.beginPath();let started=false;pts.forEach(([px,y])=>{const yy=py(y);if(!Number.isFinite(yy)||yy< -canvas.height||yy>canvas.height*2){started=false;return}if(!started){ctx.moveTo(px,yy);started=true}else ctx.lineTo(px,yy)});ctx.stroke();addHistory('Gráfico',`f(x) = ${fn}`,`Intervalo [${x0}, ${x1}]`)}$('#plotBtn').onclick=plot;plot();
function renderHistory(){const el=$('#historyList');el.innerHTML=history.length?history.map(h=>`<div class="history-item"><div><strong>${h.type}</strong><br>${h.detail}<br><small>${h.date}</small></div><b>${h.result}</b></div>`).join(''):'<div class="empty">Nenhum cálculo registrado.</div>'}$('#clearHistory').onclick=()=>{if(confirm('Deseja apagar todo o histórico?')){history=[];localStorage.removeItem('wosvipHistory');renderHistory()}};renderHistory();
